In [2]:
import pandas as pd

In [ ]:
col_name = ['지번코드', '기관코드', '일련번호', "접수년도", "자치구코드", "자치구명", "법정동코드", 
            "법정동명", "본번", "부번", "건물명", "층", "임대건물코드", "임대건물명", "임대면적", 
            "전월세구분코드", "전월세구분", "보증금", "임대료", "계약년도", "계약일자", "건축년도"]

In [20]:
df = pd.read_csv('서울특별시_전월세가_정보_2020.csv', encoding='euc-kr', sep = ';', header = None, 
                names = col_name)
df[:5]

,지번코드,기관코드,일련번호,접수년도,자치구코드,자치구명,법정동코드,법정동명,본번,부번,...,임대건물코드,임대건물명,임대면적,전월세구분코드,전월세구분,보증금,임대료,계약년도,계약일자,건축년도
0,1141011800,3120132.0,542.0,2020.0,11410.0,서대문구,11800.0,홍은동,NaN,NaN,...,2.0,단독/다가구,78.0,4.0,준전세,15000.0,30.0,2020.0,20200228.0,"1977,,,,,,"
1,1144010400105550000,3130047.0,550.0,2020.0,11440.0,마포구,10400.0,도화동,555.0,0.0,...,1.0,아파트,50.0,3.0,준월세,2000.0,150.0,2020.0,20200417.0,"2004,,,,,,"
2,1144010800106600000,3130047.0,551.0,2020.0,11440.0,마포구,10800.0,대흥동,660.0,0.0,...,1.0,아파트,59.0,1.0,전세,50000.0,0.0,2020.0,20200326.0,"1999,,,,,,"
3,1144010800107720002,3130047.0,552.0,2020.0,11440.0,마포구,10800.0,대흥동,772.0,2.0,...,4.0,다세대/연립,31.0,3.0,준월세,5000.0,100.0,2020.0,20200510.0,"2006,,,,,,"
4,1144010500103800000,3130047.0,553.0,2020.0,11440.0,마포구,10500.0,용강동,380.0,0.0,...,1.0,아파트,84.0,1.0,전세,60000.0,0.0,2020.0,20200215.0,"2003,,,,,,"

In [3]:
건축물 = pd.read_csv('Data/Project Data/4.광양시_건축물_표제부.csv')
건축물

,land_location,sgg_cd,emd_cd,land_gbn,bun,ji,bldg_nm,dong_nm,main_annex_gbn,purpose_cd,purpose_nm,etc_purpose_nm,household_cnt,family_cnt,ho_cnt,lon,lat
0,전라남도 광양시 중동 1294-1번지,46230,10600,0,"""1294""","""0001""",중동아파트,상가동,주건축물,3000,제1종근린생활시설,"제1종근린생활시설,제2종근린생황시설",0,0,6,127.699005,34.942899
1,전라남도 광양시 중동 1294번지,46230,10600,0,"""1294""","""0000""",중동아파트,108동,주건축물,2000,공동주택,주택,50,0,0,127.699693,34.943388
2,전라남도 광양시 중동 1294번지,46230,10600,0,"""1294""","""0000""",중동아파트,106동,주건축물,2000,공동주택,아파트,50,0,0,127.699693,34.943388
3,전라남도 광양시 중동 1294번지,46230,10600,0,"""1294""","""0000""",중동아파트,102동,주건축물,2000,공동주택,주택,50,0,0,127.699693,34.943388
4,전라남도 광양시 중동 1294번지,46230,10600,0,"""1294""","""0000""",중동아파트,105동,주건축물,2000,공동주택,아파트,40,0,0,127.699693,34.943388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110,전라남도 광양시 다압면 신원리 407-4번지,46230,36021,0,"""0407""","""0004""",평화를여는마을,아동,주건축물,2000,공동주택,공동주택(다세대),1,0,0,127.737085,35.058258
1111,전라남도 광양시 다압면 신원리 407-4번지,46230,36021,0,"""0407""","""0004""",평화를여는마을,가동,주건축물,2000,공동주택,공동주택(다세대주택),4,0,0,127.737085,35.058258
1112,전라남도 광양시 다압면 신원리 407-4번지,46230,36021,0,"""0407""","""0004""",평화를여는마을,라동,주건축물,2000,공동주택,공동주택(다세대),4,0,0,127.737085,35.058258
1113,전라남도 광양시 다압면 신원리 407-4번지,46230,36021,0,"""0407""","""0004""",평화를여는마을,마동,주건축물,2000,공동주택,공동주택(다세대),4,0,0,127.737085,35.058258
1114,전라남도 광양시 다압면 신원리 705-2번지,46230,36021,0,"""0705""","""0002""",NaN,신기복지회관,주건축물,11000,노유자시설,"노유자시설, 제1종근린생활시설",0,0,0,127.733015,35.065658

In [9]:
건축물 = 건축물[건축물['main_annex_gbn'] == '주건축물']
건축물

,land_location,sgg_cd,emd_cd,land_gbn,bun,ji,bldg_nm,dong_nm,main_annex_gbn,purpose_cd,purpose_nm,etc_purpose_nm,household_cnt,family_cnt,ho_cnt,lon,lat
0,전라남도 광양시 중동 1294-1번지,46230,10600,0,"""1294""","""0001""",중동아파트,상가동,주건축물,3000,제1종근린생활시설,"제1종근린생활시설,제2종근린생황시설",0,0,6,127.699005,34.942899
1,전라남도 광양시 중동 1294번지,46230,10600,0,"""1294""","""0000""",중동아파트,108동,주건축물,2000,공동주택,주택,50,0,0,127.699693,34.943388
2,전라남도 광양시 중동 1294번지,46230,10600,0,"""1294""","""0000""",중동아파트,106동,주건축물,2000,공동주택,아파트,50,0,0,127.699693,34.943388
3,전라남도 광양시 중동 1294번지,46230,10600,0,"""1294""","""0000""",중동아파트,102동,주건축물,2000,공동주택,주택,50,0,0,127.699693,34.943388
4,전라남도 광양시 중동 1294번지,46230,10600,0,"""1294""","""0000""",중동아파트,105동,주건축물,2000,공동주택,아파트,40,0,0,127.699693,34.943388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110,전라남도 광양시 다압면 신원리 407-4번지,46230,36021,0,"""0407""","""0004""",평화를여는마을,아동,주건축물,2000,공동주택,공동주택(다세대),1,0,0,127.737085,35.058258
1111,전라남도 광양시 다압면 신원리 407-4번지,46230,36021,0,"""0407""","""0004""",평화를여는마을,가동,주건축물,2000,공동주택,공동주택(다세대주택),4,0,0,127.737085,35.058258
1112,전라남도 광양시 다압면 신원리 407-4번지,46230,36021,0,"""0407""","""0004""",평화를여는마을,라동,주건축물,2000,공동주택,공동주택(다세대),4,0,0,127.737085,35.058258
1113,전라남도 광양시 다압면 신원리 407-4번지,46230,36021,0,"""0407""","""0004""",평화를여는마을,마동,주건축물,2000,공동주택,공동주택(다세대),4,0,0,127.737085,35.058258
1114,전라남도 광양시 다압면 신원리 705-2번지,46230,36021,0,"""0705""","""0002""",NaN,신기복지회관,주건축물,11000,노유자시설,"노유자시설, 제1종근린생활시설",0,0,0,127.733015,35.065658

In [8]:
건축물.to_csv('건축물.csv')